const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        //version: "1.0.0",
        title: "API - Modulo de Recursos",
        //description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "modulo-recursos-psa.herokuapp.com:5000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    definitions: {
        License: {
            licensedPerson: "Juan Zeo",
            startingDate: 29,
            durationDays: "",
            approved: 10,
            created: 10,
        },
        Hour: {
            hourCreator: "Francisco Felici",
            startingHour: 29,
            duration: "",
            projectNumber: 10,
            taskNumber: 10,
            created: "2011-04-22"
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./index.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index')           // Your project's root file
})
