# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Modulo de Recursos PSA Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DATABASE_URL: mongodb://localhost:27017/

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        mongodb-version: ['4.2', '4.4', '5.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm install
    - run: npm run build --if-present  
    - run: sudo docker build -t psa-recursos .
    - run: sudo docker run -d -p 27017:27017 mongo:${{ matrix.mongodb-version }}
    - run: sudo docker run -d -p 3000:3000 -e DATABASE_URL=$DATABASE_URL psa-recursos
    - run: sleep 10
    - run: npm test
